begin;
create schema if not exists app_private;

create table public.agents (
  id text primary key, name text not null, email text not null unique, phone text not null,
  avatar text, specialization text not null, locations text[] not null default '{}',
  languages text[] not null default '{}', status text not null default 'ACTIVE' check (status in ('ACTIVE','INACTIVE'))
);
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade, name text not null,
  role text not null check (role in ('ADMIN','AGENT')), agent_id text unique references public.agents(id),
  created_at timestamptz not null default now(), check (role <> 'AGENT' or agent_id is not null)
);
create table public.properties (
  id bigint generated by default as identity primary key, slug text not null unique, title text not null,
  category text not null, purpose text not null check (purpose in ('buy','rent','off-plan','commercial')),
  location text not null, location_slug text not null, city text not null default 'Dubai',
  price numeric(16,2) not null check (price > 0), currency text not null default 'AED',
  bedrooms integer not null default 0 check (bedrooms >= 0), bathrooms integer not null default 0 check (bathrooms >= 0),
  area numeric not null check (area > 0), area_unit text not null default 'sq ft', featured boolean not null default false,
  off_plan boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  tenure text default 'Freehold', furnished text default 'Unfurnished', reference text, images text[] not null,
  coordinates jsonb not null default '{"lat":25.2048,"lng":55.2708}', description text not null,
  amenities text[] not null default '{}', agent jsonb not null default '{}',
  status text not null default 'DRAFT' check (status in ('ACTIVE','DRAFT','SOLD','RENTED','INACTIVE')),
  check (cardinality(images) > 0)
);
create table public.leads (
  id text primary key default ('LEAD-' || gen_random_uuid()::text),
  customer_name text not null, customer_email text not null, customer_phone text not null, customer_country text not null,
  property_id bigint references public.properties(id), source text not null, purpose text not null default 'buy',
  budget_min numeric(16,2) not null default 0 check (budget_min >= 0), budget_max numeric(16,2) not null default 0 check (budget_max >= 0),
  preferred_location text not null default '', preferred_contact text not null default 'Call',
  status text not null default 'NEW' check (status in ('NEW','ASSIGNED','CONTACTED','QUALIFIED','FOLLOW_UP','VIEWING_SCHEDULED','VIEWING_COMPLETED','NEGOTIATION','WON','LOST')),
  priority text not null default 'MEDIUM' check (priority in ('LOW','MEDIUM','HIGH','URGENT')),
  assigned_agent_id text references public.agents(id), assigned_at timestamptz, next_follow_up timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  final_property_id bigint references public.properties(id), deal_value numeric(16,2) check (deal_value > 0), closing_date timestamptz, deal_notes text,
  lost_reason text, lost_notes text,
  check (status <> 'WON' or (deal_value is not null and final_property_id is not null and closing_date is not null)),
  check (status <> 'LOST' or nullif(lost_reason,'') is not null)
);
create table public.lead_activities (
  id text primary key default ('ACT-' || gen_random_uuid()::text), lead_id text not null references public.leads(id),
  type text not null, message text not null, author text not null, author_profile_id uuid references public.profiles(id),
  created_at timestamptz not null default now()
);
create table public.lead_notes (
  id text primary key default ('NOTE-' || gen_random_uuid()::text), lead_id text not null references public.leads(id),
  content text not null check (length(content) between 1 and 10000), author text not null,
  author_profile_id uuid references public.profiles(id), created_at timestamptz not null default now()
);
create table public.tasks (
  id text primary key default ('TASK-' || gen_random_uuid()::text), lead_id text not null references public.leads(id),
  agent_id text not null references public.agents(id), title text not null, type text not null default 'Call',
  due_date timestamptz not null, priority text not null default 'MEDIUM' check (priority in ('LOW','MEDIUM','HIGH','URGENT')),
  status text not null default 'PENDING' check (status in ('PENDING','IN_PROGRESS','COMPLETED','CANCELLED')),
  notes text not null default '', is_follow_up boolean not null default false
);
create table public.viewings (
  id text primary key default ('VIEW-' || gen_random_uuid()::text), lead_id text not null references public.leads(id),
  property_id bigint not null references public.properties(id), agent_id text not null references public.agents(id),
  date timestamptz not null, meeting_location text not null, notes text not null default '',
  status text not null default 'SCHEDULED' check (status in ('SCHEDULED','COMPLETED','CANCELLED')),
  outcome text, outcome_notes text, completed_at timestamptz
);
create table public.notifications (
  id text primary key default ('NOTICE-' || gen_random_uuid()::text), lead_id text not null references public.leads(id),
  agent_id text references public.agents(id), message text not null, created_at timestamptz not null default now(), read_by text[] not null default '{}'
);
create table public.crm_settings (
  id integer primary key default 1 check (id = 1), company text not null, email text not null,
  phone text not null, default_view text not null default 'table' check (default_view in ('table','kanban'))
);
create table public.public_content (kind text primary key, data jsonb not null, updated_at timestamptz not null default now());
create table public.newsletter_subscriptions (email text primary key, created_at timestamptz not null default now());
create table public.visitor_preferences (token_hash text primary key, favorites bigint[] not null default '{}', updated_at timestamptz not null default now());

create index leads_agent_status on public.leads(assigned_agent_id,status);
create index leads_created_at on public.leads(created_at desc);
create index tasks_agent_due on public.tasks(agent_id,due_date);
create index tasks_lead on public.tasks(lead_id);
create index viewings_agent_date on public.viewings(agent_id,date);
create index activities_lead_created on public.lead_activities(lead_id,created_at desc);
create index notes_lead on public.lead_notes(lead_id);
create index notifications_agent_created on public.notifications(agent_id,created_at desc);
create index properties_status on public.properties(status);

create function app_private.is_admin() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'ADMIN');
$$;
create function app_private.agent_id() returns text language sql stable security definer set search_path = '' as $$
  select p.agent_id from public.profiles p where id = auth.uid();
$$;
create function app_private.has_profile() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where id = auth.uid());
$$;
create function app_private.can_read_lead(lead_key text) returns boolean language sql stable security definer set search_path = '' as $$
  select app_private.is_admin() or exists(select 1 from public.leads where id = lead_key and assigned_agent_id = app_private.agent_id());
$$;

alter table public.profiles enable row level security;
alter table public.agents enable row level security;
alter table public.properties enable row level security;
alter table public.leads enable row level security;
alter table public.lead_activities enable row level security;
alter table public.lead_notes enable row level security;
alter table public.tasks enable row level security;
alter table public.viewings enable row level security;
alter table public.notifications enable row level security;
alter table public.crm_settings enable row level security;
alter table public.public_content enable row level security;
alter table public.newsletter_subscriptions enable row level security;
alter table public.visitor_preferences enable row level security;

create policy profiles_read on public.profiles for select to authenticated using (id = (select auth.uid()) or (select app_private.is_admin()));
create policy agents_read on public.agents for select to authenticated using ((select app_private.is_admin()) or id = (select app_private.agent_id()));
create policy properties_read on public.properties for select to anon,authenticated using (status = 'ACTIVE' or (select app_private.has_profile()));
create policy leads_read on public.leads for select to authenticated using ((select app_private.is_admin()) or assigned_agent_id = (select app_private.agent_id()));
create policy activities_read on public.lead_activities for select to authenticated using (app_private.can_read_lead(lead_id));
create policy notes_read on public.lead_notes for select to authenticated using (app_private.can_read_lead(lead_id));
create policy tasks_read on public.tasks for select to authenticated using (app_private.can_read_lead(lead_id) and ((select app_private.is_admin()) or agent_id = (select app_private.agent_id())));
create policy viewings_read on public.viewings for select to authenticated using (app_private.can_read_lead(lead_id) and ((select app_private.is_admin()) or agent_id = (select app_private.agent_id())));
create policy notifications_read on public.notifications for select to authenticated using ((select app_private.is_admin()) or (agent_id = (select app_private.agent_id()) and app_private.can_read_lead(lead_id)));
create policy settings_read on public.crm_settings for select to authenticated using ((select app_private.has_profile()));
create policy content_read on public.public_content for select to anon,authenticated using (true);

revoke all on public.profiles,public.agents,public.properties,public.leads,public.lead_activities,public.lead_notes,public.tasks,public.viewings,public.notifications,public.crm_settings,public.public_content,public.newsletter_subscriptions,public.visitor_preferences from anon,authenticated;
grant all on public.profiles,public.agents,public.properties,public.leads,public.lead_activities,public.lead_notes,public.tasks,public.viewings,public.notifications,public.crm_settings,public.public_content,public.newsletter_subscriptions,public.visitor_preferences to service_role;
grant usage, select on sequence public.properties_id_seq to service_role;
grant select on public.properties,public.public_content to anon,authenticated;
grant select on public.profiles,public.agents,public.leads,public.lead_activities,public.lead_notes,public.tasks,public.viewings,public.notifications,public.crm_settings to authenticated;
revoke all on all functions in schema app_private from public,anon,authenticated;
grant usage on schema app_private to anon,authenticated;
grant execute on function app_private.is_admin(),app_private.agent_id(),app_private.has_profile(),app_private.can_read_lead(text) to anon,authenticated;
commit;
